### PR TITLE
adjusted array misalignment

### PR DESCRIPTION
**Pull request by shannona**

### CODE REVIEW

**Review by wolfmcnally — COMMENTED** [review]
This is incorrect: Shell arrays use a 1-based count.

**Comment by wolfmcnally** [comment]
The code is actually correct as is.

**Comment by shannona** [comment]
It looks like that's true for zsh, but not for bash. Mac went to zsh as the default in 2019, so yep your way is correct, but there are likely enough people using bash that we need to flag it somehow. (I didn't even know I was using an out of date Shell.)

[in bash]:
$ ALICE_KNOWS_BOB=ur:envelope/lftpsptpuoihfpjziniaihtpsptputlftpsptpuoihjejtjlktjktpsptpuoiafwjlidrdpdiesk
$ SHARE_ENVELOPES=(`envelope sskr split -g 2-of-3 $ALICE_KNOWS_BOB`)
$ echo ${SHARE_ENVELOPES[1]}
ur:envelope/lftpsptpsolrhddkhffwlkoyetrlrtclcxwzpkwdcawmlrntbszsbdlubkglzmjysfryhgislalguemtfhoneomugshptegelowpaojylanlgowsqdgdatotkicldszclgbgiywybdtttsryfrmyhddktpsbhdcxdsdacwememuoztpkmsamkbkolbutoxjztagmjymdjsmkdinlrnmokbjtttemdwditpsptputlftpsptpuramtpsptpuotaadechddakontaeadadqzvyglbeghmskilegyghytclzttlgmmevaluvtcegahdisdnahdwadtdkkchaxgscpteynas
$ echo ${SHARE_ENVELOPES[2]}
ur:envelope/lftpsptpsolrhddkhffwlkoyetrlrtclcxwzpkwdcawmlrntbszsbdlubkglzmjysfryhgislalguemtfhoneomugshptegelowpaojylanlgowsqdgdatotkicldszclgbgiywybdtttsryfrmyhddktpsbhdcxdsdacwememuoztpkmsamkbkolbutoxjztagmjymdjsmkdinlrnmokbjtttemdwditpsptputlftpsptpuramtpsptpuotaadechddakontaeadaodsaavoldehfmkededsbneskpmnrhssjsrdwnpfkegmletnghzemywmplgloylptbstsfzokt
$ echo ${SHARE_ENVELOPES[3]}

$ echo ${SHARE_ENVELOPES[0]}
ur:envelope/lftpsptpsolrhddkhffwlkoyetrlrtclcxwzpkwdcawmlrntbszsbdlubkglzmjysfryhgislalguemtfhoneomugshptegelowpaojylanlgowsqdgdatotkicldszclgbgiywybdtttsryfrmyhddktpsbhdcxdsdacwememuoztpkmsamkbkolbutoxjztagmjymdjsmkdinlrnmokbjtttemdwditpsptputlftpsptpuramtpsptpuotaadechddakontaeadaeeogrdrioktwtlucakemdrhvetdwncxettdghtifnfzcmamylongtplbsntlklofttatipskb

**Comment by shannona** [comment]
Ah, here we go:

> Zsh is only the default shell on newly created user accounts, so any existing accounts you have on an upgraded  Mac will still use Bash by default unless you change it. Each user account has its own default shell preference.

So any Mac user who's been using a Mac for three years or more is likely still using bash. Which could easily be most users.

**Pull request closed without merging**
